### ISSUE TITLE
zlib download link incorrect

### ISSUE THREAD

**Issue by Neusbeer** [Arachni/build-scripts#5]
build.sh has incorrect link for the zlib tar.

--2017-01-31 16:31:09--  http://zlib.net/zlib-1.2.10.tar.gz
Resolving zlib.net (zlib.net)... 69.73.132.10
Connecting to zlib.net (zlib.net)|69.73.132.10|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-01-31 16:31:10 ERROR 404: Not Found.

it has updated 
zlib 1.2.11
January 15, 2017

It has changed to http://zlib.net/zlib-1.2.11.tar.gz

**Comment by Zapotek** [comment]
This has become really annoying, they keep switching it out with every release.

**Comment by Neusbeer** [comment]
that's annoying indeed.
grep line 11 of http://www.zlib.net/manual.html to get version add as var
like [0-9]\.[0-9]\.[0-9]{2}
or add it to this git. :)
