### ISSUE TITLE
Issues running build script, ncurses and rubygems

### ISSUE THREAD

**Issue by bgerardw** [Arachni/build-scripts#6]
I am following  your development build process as described on:
https://github.com/Arachni/arachni/wiki/Development-environment. I am however running into a number of issues.
Some I have used workarounds for. I thought it might be beneficial if I recorded them for you.

I initially had an issue with installing ncurses.
It fails after compiling the error log  has the message.

```
../include/curses.h:1631:56: note: in definition of macro ‘mouse_trafo’
#define mouse_trafo(y,x,to_screen) wmouse_trafo(stdscr,y,x,to_screen)
                                                    ^
Makefile:962: recipe for target '../objects/lib_gen.o' failed
```

I traced the issue to this thread https://stackoverflow.com/questions/37475222/ncurses-6-0-compilation-error-error-expected-before-int

I rectified it by adding to your code CPPFLAGS="-P"

`configure_ncurses="CPPFLAGS=\"-P\" CFLAGS=-fPIC ./configure"`

```
* Extracting
/home/brian/Projects/arachni-build-dir/arachni/build/src/ncurses-6.0
  * Cleaning
  * Configuring (CPPFLAGS="-P" CFLAGS=-fPIC ./configure --prefix=/home/brian/Projects/arachni-build-dir/arachni/system/usr)
  * Compiling
  * Installing
```

However having done all this I deleted my arachni-build-dir and ran :
`ARACHNI_BUILD_ENV=development wget -O - https://raw.github.com/Arachni/build-scripts/master/bootstrap.sh | bash`

`The ncurses issue had vanished.

Now I am getting an error on Rubygems(it seems to also be an issue for bundler).

The error log reads: 

```
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)
```

I was directed to this solution.

http://guides.rubygems.org/ssl-certificate-update/#installing-using-update-packages

I can also address the issue by substituting a newer version of ruby. I tested this with 2.4 and it addressed the rubymine and bundler issues. However it seems to cause an issue with certain gems during their install for arachni-web-ui.

Any guidance would be appreciated.

**Comment by Zapotek** [comment]
Thanks for the ncurses tip, I'll incorporate it in the script.
As for the SSL error, I think that you need to download an updated certificate, I don't remember where from at the moment but I'll do some digging and let you know.

Regarding Ruby 2.4.0, it won't work for the reason you mentioned, some dependencies haven't been updated for it yet.

Until then, you can setup your end manually by installing these dependencies: https://github.com/Arachni/arachni/wiki/Installation#nix-source-based
PhantomJS won't be installed via `apt-get` though, you'll need to download it yourself.

Cheers

**Comment by bgerardw** [comment]
Out of curiosity I edited the script to use ruby 2.3.3(as the manual process supports it)  and it seemed to address the issue.

**Comment by Zapotek** [comment]
Some dependencies didn't use to support it, on Windows I think, so I stuck it out with 2.2.3 for the time being.
It is time for a upgrade though, at least for the *nix packages.

**Comment by bgerardw** [comment]
I am on Ubuntu 16.04/01 LTS

**Comment by Zapotek** [comment]
I fixed the SSL issue, everything should work fine now.

**Comment by Zapotek** [comment]
I forgot to mention that the issue is still there on the MS Windows version for Ruby 2.3.x so I'll be sticking with v2.2.3 for all packages to ensure an identical environment.
