### ISSUE TITLE
build self-contained packages from source

### ISSUE THREAD

**Issue by b1ngz** [Arachni/build-scripts#7]
Hi, I fork arachni and modify some code, and i want to build self-contained packages from it, I have tried build-scripts，it seems for the official arachni, how can i modify the script to build from my repository?

**Comment by Zapotek** [comment]
The build scripts pull in the [WebUI](https://github.com/Arachni/build-scripts/blob/master/lib/setenv.sh#L35) which then pulls in the [framework](https://github.com/Arachni/arachni-ui-web/blob/experimental/Gemfile#L100), there's no straightforward way to just build a package for the framework.

Also, I don't know what your intentions are, but please check the license: https://github.com/Arachni/arachni/blob/experimental/LICENSE.md
