### ISSUE TITLE
The build of the experimental version of Arachni doesn't work...

### ISSUE THREAD

**Issue by gianogli** [Arachni/build-scripts#9]
If I run the build command on a Debian Testing:
``wget -O - https://raw.github.com/Arachni/build-scripts/master/bootstrap.sh | bash``
and I obtain this error:
```
## (12/12) fontconfig
  * Downloading https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.11.1.tar.gz                           
  * Extracting
  * Cleaning
  * Configuring (FREETYPE_CFLAGS="-I/usr/local/src/arachni_git/arachni-build-dir/arachni/system/usr/include/freetype2" FREETYPE_LIBS="-L/usr/local/src/arachni_git/arachni-build-dir/arachni/system/usr/lib -lfreetype -lz" ./configure --with-expat=/usr/local/src/arachni_git/arachni-build-dir/arachni/system/usr --prefix=/usr/local/src/arachni_git/arachni-build-dir/arachni/system/usr)
  * Compiling
Build failed, check /usr/local/src/arachni_git/arachni-build-dir/arachni/build/logs/fontconfig for details.
When you resolve the issue you can run the script again to continue where the process left off.
```
I resolved this issue with this patch 
[0001-Avoid-conflicts-with-integer-width-macros-from-TS-18.txt](https://github.com/Arachni/build-scripts/files/2339374/0001-Avoid-conflicts-with-integer-width-macros-from-TS-18.txt)

but if I run again the build command now I obtain this new error:
```
# (6/7) Installing Arachni
-------------------------------
  * Installing
Build failed, check /usr/local/src/arachni_git/arachni-build-dir/arachni/build/logs/arachni-ui-web for details.
When you resolve the issue you can run the script again to continue where the process left off.
```
The issue is related to the used ruby version that is < 2.3 (now the build script is downloading automatically the version 2.2.3).

Could you solve this problems?

Thanks...

**Comment by Zapotek** [comment]
Hello,

I've been making some updates on Arachni's dependencies but I haven't gotten to the build scripts yet.

**Comment by Zapotek** [comment]
I'm not sure about fontconfig yet but the Ruby issue has been resolved.

**Comment by gianogli** [comment]
Ok, now it works!
(The issue related to fontconfig remains, but I think is related to my environment: debian testing)
